/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectx;

import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class reservation extends javax.swing.JFrame {
        boolean check;

    /**
     * Creates new form reservation
     */
   public reservation() {
        initComponents();
        this.reshape(400, 200, 660, 480);
        
    }
        public reservation(String name, theatre [] found ) {
    
           initComponents();
            this.reshape(400, 200, 660, 438);
        movienameLabel.setText(name);
        
        
        
        if(found[0]==null){
        theater_lbl.setText(""); 
            Button01.setVisible(false);
         Button02.setVisible(false);
         Button03.setVisible(false);
        }
        else
            theater_lbl.setText(found[0].getName()); 
        
        if(found[1]==null){
        theater_lbl1.setText(""); 
            Button11.setVisible(false);
         Button12.setVisible(false);
         Button13.setVisible(false);
        }
        else
            theater_lbl1.setText(found[1].getName()); 
        
      if(found[2]==null){
        theater_lbl2.setText(""); 
            Button21.setVisible(false);
         Button22.setVisible(false);
         Button23.setVisible(false);
      }
        else
            theater_lbl2.setText(found[2].getName()); 
        
      if(found[3]==null)
      {
        theater_lbl3.setText(""); 
         Button30.setVisible(false);
         Button31.setVisible(false);
         Button32.setVisible(false);
      }
      
        else
            theater_lbl3.setText(found[3].getName()); 
        
       if(found[4]==null)
       {
        lbl5.setText("");
         Button51.setVisible(false);
         Button52.setVisible(false);
         Button53.setVisible(false);
       }
        else
            lbl5.setText(found[4].getName()); 
        
             }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        movienameLabel = new javax.swing.JLabel();
        theater_lbl = new javax.swing.JLabel();
        theater_lbl1 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        Button52 = new javax.swing.JButton();
        Button51 = new javax.swing.JButton();
        Button53 = new javax.swing.JButton();
        Button21 = new javax.swing.JButton();
        Button22 = new javax.swing.JButton();
        Button23 = new javax.swing.JButton();
        Button11 = new javax.swing.JButton();
        Button12 = new javax.swing.JButton();
        Button13 = new javax.swing.JButton();
        Button01 = new javax.swing.JButton();
        Button02 = new javax.swing.JButton();
        Button03 = new javax.swing.JButton();
        theater_lbl2 = new javax.swing.JLabel();
        Button30 = new javax.swing.JButton();
        Button31 = new javax.swing.JButton();
        Button32 = new javax.swing.JButton();
        theater_lbl3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        movienameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        movienameLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(movienameLabel);
        movienameLabel.setBounds(10, 0, 310, 36);

        theater_lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(theater_lbl);
        theater_lbl.setBounds(30, 60, 130, 28);

        theater_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(theater_lbl1);
        theater_lbl1.setBounds(30, 130, 130, 29);

        lbl5.setBackground(new java.awt.Color(255, 255, 255));
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl5);
        lbl5.setBounds(10, 340, 130, 32);

        Button52.setText("From 5 to 8");
        Button52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button52ActionPerformed(evt);
            }
        });
        getContentPane().add(Button52);
        Button52.setBounds(310, 340, 120, 23);

        Button51.setText("From 2 to 5");
        Button51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button51ActionPerformed(evt);
            }
        });
        getContentPane().add(Button51);
        Button51.setBounds(170, 340, 130, 23);

        Button53.setText("From 8 to 11");
        Button53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button53ActionPerformed(evt);
            }
        });
        getContentPane().add(Button53);
        Button53.setBounds(440, 340, 140, 23);

        Button21.setText("From 2 to 5");
        Button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button21ActionPerformed(evt);
            }
        });
        getContentPane().add(Button21);
        Button21.setBounds(170, 200, 130, 23);

        Button22.setText("From 5 to 8");
        Button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button22ActionPerformed(evt);
            }
        });
        getContentPane().add(Button22);
        Button22.setBounds(310, 200, 120, 23);

        Button23.setText("From 8 to 11");
        Button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button23ActionPerformed(evt);
            }
        });
        getContentPane().add(Button23);
        Button23.setBounds(440, 200, 140, 23);

        Button11.setText("From 2 to 5");
        Button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button11ActionPerformed(evt);
            }
        });
        getContentPane().add(Button11);
        Button11.setBounds(170, 130, 130, 23);

        Button12.setText("From 5 to 8");
        Button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button12ActionPerformed(evt);
            }
        });
        getContentPane().add(Button12);
        Button12.setBounds(310, 130, 120, 23);

        Button13.setText("From 8 to 11");
        Button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button13ActionPerformed(evt);
            }
        });
        getContentPane().add(Button13);
        Button13.setBounds(440, 130, 140, 23);

        Button01.setText("From 2 to 5");
        Button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button01ActionPerformed(evt);
            }
        });
        getContentPane().add(Button01);
        Button01.setBounds(170, 60, 130, 23);

        Button02.setText("From 5 to 8");
        Button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button02ActionPerformed(evt);
            }
        });
        getContentPane().add(Button02);
        Button02.setBounds(310, 60, 120, 23);

        Button03.setText("From 8 to 11");
        Button03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button03ActionPerformed(evt);
            }
        });
        getContentPane().add(Button03);
        Button03.setBounds(440, 60, 140, 23);

        theater_lbl2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(theater_lbl2);
        theater_lbl2.setBounds(20, 200, 130, 34);

        Button30.setText("From 2 to 5");
        Button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button30ActionPerformed(evt);
            }
        });
        getContentPane().add(Button30);
        Button30.setBounds(170, 270, 130, 23);

        Button31.setText("From 5 to 8");
        Button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button31ActionPerformed(evt);
            }
        });
        getContentPane().add(Button31);
        Button31.setBounds(310, 270, 120, 23);

        Button32.setText("From 8 to 11");
        Button32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button32ActionPerformed(evt);
            }
        });
        getContentPane().add(Button32);
        Button32.setBounds(440, 270, 140, 23);

        theater_lbl3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(theater_lbl3);
        theater_lbl3.setBounds(30, 270, 117, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button31ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl3.getText(), Button31.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button31ActionPerformed

    private void Button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button01ActionPerformed
        // TODO add your handling code here:
        show s1 = new show();
       check= s1.seatsinShow(theater_lbl.getText(), Button01.getText());
        
        if (check == true )
        {
            payment pay = new payment();
            pay.setVisible(true);
            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
            
    }//GEN-LAST:event_Button01ActionPerformed

    private void Button02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button02ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl.getText(), Button02.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
            
    }//GEN-LAST:event_Button02ActionPerformed

    private void Button03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button03ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl.getText(), Button03.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
            
    }//GEN-LAST:event_Button03ActionPerformed

    private void Button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button12ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl1.getText(), Button12.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button12ActionPerformed

    private void Button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button11ActionPerformed
 show s1 = new show();
       check= s1.seatsinShow(theater_lbl1.getText(), Button11.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button11ActionPerformed

    private void Button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button13ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl1.getText(), Button13.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button13ActionPerformed

    private void Button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button21ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl2.getText(), Button21.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button21ActionPerformed

    private void Button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button22ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl2.getText(), Button22.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button22ActionPerformed

    private void Button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button23ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl2.getText(), Button23.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button23ActionPerformed

    private void Button30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button30ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl3.getText(), Button30.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button30ActionPerformed

    private void Button32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button32ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(theater_lbl3.getText(), Button32.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button32ActionPerformed

    private void Button51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button51ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(lbl5.getText(), Button51.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button51ActionPerformed

    private void Button52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button52ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(lbl5.getText(), Button52.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button52ActionPerformed

    private void Button53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button53ActionPerformed
        // TODO add your handling code here:
         show s1 = new show();
       check= s1.seatsinShow(lbl5.getText(), Button53.getText());
        
        if (check == true )
        {

            payment pay = new payment();
            pay.setVisible(true);            
        }
        else 
            JOptionPane.showConfirmDialog(this, "error", "theatre is full could'nt reserve ", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Button53ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button01;
    private javax.swing.JButton Button02;
    private javax.swing.JButton Button03;
    private javax.swing.JButton Button11;
    private javax.swing.JButton Button12;
    private javax.swing.JButton Button13;
    private javax.swing.JButton Button21;
    private javax.swing.JButton Button22;
    private javax.swing.JButton Button23;
    private javax.swing.JButton Button30;
    private javax.swing.JButton Button31;
    private javax.swing.JButton Button32;
    private javax.swing.JButton Button51;
    private javax.swing.JButton Button52;
    private javax.swing.JButton Button53;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel movienameLabel;
    private javax.swing.JLabel theater_lbl;
    private javax.swing.JLabel theater_lbl1;
    private javax.swing.JLabel theater_lbl2;
    private javax.swing.JLabel theater_lbl3;
    // End of variables declaration//GEN-END:variables
}
